---
- hosts: 127.0.0.1
  tasks:
  - name: Get Jenkins repo
    action: get_url url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

  - name: Import Jenkins repo key
    action: command rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

  - name: Install Jenkins
    action: yum name=jenkins

  - name: Start Jenkins service
    action: service name=jenkins state=started

  - name: Install nginx
    action: yum name=nginx

  - name: Configure nginx
    action: template src=nginx-default.conf dest=/etc/nginx/conf.d/default.conf

  - name: Start nginx
    action: service name=nginx state=started
